/*globals define, _*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Wed Jun 15 2016 14:06:10 GMT-0500 (CDT).
 */

define([
    'widgets/TextEditor/TextEditorWidget',
    'css!./styles/LogViewerWidget.css'
], function (
    TextEditorWidget
) {
    'use strict';

    var LogViewerWidget;

    LogViewerWidget = function () {
        this.readOnly = true;
        TextEditorWidget.apply(this, arguments);
        this.editor.setTheme('ace/theme/twilight');
        this.editor.setShowPrintMargin(false);
    };

    _.extend(LogViewerWidget.prototype, TextEditorWidget.prototype);

    LogViewerWidget.prototype.getHeader = function(desc) {
        return `Console logging for Operation "${desc.name}":\n`;
    };

    LogViewerWidget.prototype.getSessionOptions = function() {
        return {
            firstLineNumber: -1
        };
    };

    LogViewerWidget.prototype.getEditorOptions = function() {
        return {
            fontSize: '10pt'
        };
    };

    return LogViewerWidget;
});
