/*globals define, WebGMEGlobal*/
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Wed May 18 2016 12:00:46 GMT-0500 (CDT).
 */

define([
    'panels/TextEditor/TextEditorControl',
    'underscore'
], function (
    TextEditorControl,
    _
) {

    'use strict';

    var OperationEditorControl;

    OperationEditorControl = function (options) {
        options.attributeName = 'code';
        TextEditorControl.call(this, options);
    };

    _.extend(OperationEditorControl.prototype, TextEditorControl.prototype);

    // Override ObjectDescriptor
    OperationEditorControl.prototype._getObjectDescriptor = function (id) {
        var desc = TextEditorControl.prototype._getObjectDescriptor.call(this, id),
            node = this._client.getNode(id);
	// Add the inputs, outputs, references, and attributes
        desc.inputs = this._parseArgs(node.getAttribute('inputs'));
        desc.outputs = this._parseArgs(node.getAttribute('outputs'));
        desc.references = node.getPointerNames().filter(name => name !== 'base');
        return desc;
    };

    // This will be changed when the input/output reps are updated (soon)
    OperationEditorControl.prototype._parseArgs = function (args) {
        // parse arguments are in the form 'arg: Type1, arg2: Type2'
        // and return [[arg1, Type1], [arg2, Type2]]
        return args ? args.split(',')
            .map(pair => pair.split(':').map(w => w.replace(/\s+/g, ''))) : [];

    };

    return OperationEditorControl;
});
