/*globals define*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue May 24 2016 10:15:19 GMT-0500 (CDT).
 */

define([
    'widgets/PipelineEditor/PipelineEditorWidget',
    './SelectionManager',
    'underscore',
    'css!./styles/ExecutionViewWidget.css'
], function (
    PipelineEditorWidget,
    SelectionManager,
    _
) {
    'use strict';

    var ExecutionViewWidget;

    ExecutionViewWidget = function (logger, container) {
        PipelineEditorWidget.call(this, logger, container);
    };

    _.extend(ExecutionViewWidget.prototype, PipelineEditorWidget.prototype);

    ExecutionViewWidget.prototype.SelectionManager = SelectionManager;

    return ExecutionViewWidget;
});
