/*globals define*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue May 24 2016 10:15:19 GMT-0500 (CDT).
 */

define([
    'widgets/EasyDAG/EasyDAGWidget',
    './SelectionManager',
    'underscore',
    'css!./styles/ExecutionViewWidget.css'
], function (
    EasyDAGWidget,
    SelectionManager,
    _
) {
    'use strict';

    var ExecutionViewWidget;

    ExecutionViewWidget = function (logger, container) {
        EasyDAGWidget.call(this, logger, container);
        this.isSnapshot = true;
    };

    _.extend(ExecutionViewWidget.prototype, EasyDAGWidget.prototype);

    ExecutionViewWidget.prototype.SelectionManager = SelectionManager;

    ExecutionViewWidget.prototype.setSnapshot = function(bool) {
        this.isSnapshot = bool;
        this.setTitle();
    };

    ExecutionViewWidget.prototype.setTitle = function(nodeName) {
        var title = nodeName === undefined ? this._currentTitle : nodeName;

        this._currentTitle = title;
        if (this.isSnapshot) {
            title += ' (SNAPSHOT)';
        }

        this._setTitle(title);
    };

    return ExecutionViewWidget;
});
