/*globals define*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue May 17 2016 11:25:46 GMT-0400 (EDT).
 */

define([
    'widgets/EasyDAG/EasyDAGWidget',
    './Layer',
    'underscore',
    'css!./styles/ArchEditorWidget.css'
], function (
    EasyDAGWidget,
    Layer,
    _
) {
    'use strict';

    var ArchEditorWidget,
        // WIDGET_CLASS = 'arch-editor',
        DEFAULT_COLOR = '#ffb74d',
        LAYER_COLORS = {
            Containers: '#ffb74d',
            Module: '#ba68c8',
            ConvLayer: '#2196f3',
            SimpleLayer: '#ff9100',
            TransferLayer: '#80deea',
            MiscLayers: '#ce93d8',
            Criterion: '#7e57c2'
        };

    ArchEditorWidget = function (logger, container) {
        EasyDAGWidget.call(this, logger, container);
        this.LAYER_COLORS = _.extend(LAYER_COLORS, this._config.LayerColors);
        this.DEFAULT_COLOR = this._config.DefaultColor || DEFAULT_COLOR;
    };

    _.extend(ArchEditorWidget.prototype, EasyDAGWidget.prototype);

    ArchEditorWidget.prototype.ItemClass = Layer;
    ArchEditorWidget.prototype.getComponentId = function() {
        return 'ArchEditor';
    };

    ArchEditorWidget.prototype.addNode = function(desc) {
        // Assign a color!
        desc.color = this.getColor(desc) || null;
        return EasyDAGWidget.prototype.addNode.call(this, desc);
    };

    ArchEditorWidget.prototype.getColor = function(desc) {
        // Assign by the layerType
        var color = this.LAYER_COLORS[desc.layerType];
        if (!color) {
            this._logger.warn(`No color found for ${desc.layerType}`);
            color = this.DEFAULT_COLOR;
        }
        return color;
    };

    return ArchEditorWidget;
});
