/*globals define*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue May 17 2016 11:25:46 GMT-0400 (EDT).
 */

define([
    'widgets/EasyDAG/EasyDAGWidget',
    './Layer',
    'underscore',
    'css!./styles/ArchEditorWidget.css'
], function (
    EasyDAGWidget,
    Layer,
    _
) {
    'use strict';

    var ArchEditorWidget;
        // WIDGET_CLASS = 'arch-editor',

    ArchEditorWidget = function (logger, container) {
        EasyDAGWidget.call(this, logger, container);
    };

    _.extend(ArchEditorWidget.prototype, EasyDAGWidget.prototype);

    ArchEditorWidget.prototype.ItemClass = Layer;

    return ArchEditorWidget;
});
