/*globals define, WebGMEGlobal*/
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue May 17 2016 11:25:46 GMT-0400 (EDT).
 */

define([
    'widgets/EasyDAG/EasyDAGWidget',
    './Layer',
    'underscore',
    'css!./styles/ArchEditorWidget.css'
], function (
    EasyDAGWidget,
    Layer,
    _
) {
    'use strict';

    var ArchEditorWidget,
        WIDGET_CLASS = 'arch-editor',
        COLORS = [
            '#ffb74d',
            '#ba68c8',
            '#7e57c2',
            '#ff9100',
            '#2196f3',
            '#80deea'
        ];

    ArchEditorWidget = function (logger, container) {
        EasyDAGWidget.call(this, logger, container);
    };

    _.extend(ArchEditorWidget.prototype, EasyDAGWidget.prototype);

    ArchEditorWidget.prototype.ItemClass = Layer;
    ArchEditorWidget.prototype.getComponentId = function() {
        return 'ArchEditor';
    };

    ArchEditorWidget.prototype.addNode = function(desc) {
        // Assign a color!
        desc.color = this.getColor(desc) || null;
        return EasyDAGWidget.prototype.addNode.call(this, desc);
    };

    ArchEditorWidget.prototype.getColor = function(desc) {
        // Dumb assignment for now
        var index = Math.floor(Math.random()*COLORS.length);
        return COLORS[index];
    };

    return ArchEditorWidget;
});
