/*globals define */
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Mon May 04 2020 17:09:31 GMT-0500 (Central Daylight Time).
 */

define([
    'panels/InteractiveEditor/InteractiveEditorControl',
], function (
    InteractiveEditorControl,
) {

    'use strict';

    class TensorPlotterControl extends InteractiveEditorControl {

        getObjectDescriptor(nodeId) {
            const desc = super.getObjectDescriptor(nodeId);

            if (desc) {
                const node = this._client.getNode(nodeId);
                desc.data = node.getAttribute('data');
                desc.type = node.getAttribute('type');
            }

            return desc;
        }
    }

    return TensorPlotterControl;
});
