/*globals define*/
/*jshint node:true, browser:true*/

/**
 * Generated by PluginGenerator 0.14.0 from webgme on Thu Mar 10 2016 04:16:02 GMT-0600 (CST).
 */

define([
    'plugin/PluginConfig',
    'plugin/PluginBase'
], function (
    PluginConfig,
    PluginBase) {
    'use strict';

    /**
     * Initializes a new instance of ImportTorch.
     * @class
     * @augments {PluginBase}
     * @classdesc This class represents the plugin ImportTorch.
     * @constructor
     */
    var ImportTorch = function () {
        // Call base class' constructor.
        PluginBase.call(this);
    };

    // Prototypal inheritance from PluginBase.
    ImportTorch.prototype = Object.create(PluginBase.prototype);
    ImportTorch.prototype.constructor = ImportTorch;

    /**
     * Gets the name of the ImportTorch.
     * @returns {string} The name of the plugin.
     * @public
     */
    ImportTorch.prototype.getName = function () {
        return 'ImportTorch';
    };

    /**
     * Gets the semantic version (semver.org) of the ImportTorch.
     * @returns {string} The version of the plugin.
     * @public
     */
    ImportTorch.prototype.getVersion = function () {
        return '0.1.0';
    };

    /**
     * Gets the configuration structure for the ImportTorch.
     * The ConfigurationStructure defines the configuration for the plugin
     * and will be used to populate the GUI when invoking the plugin from webGME.
     * @returns {object} The version of the plugin.
     * @public
     */
    ImportTorch.prototype.getConfigStructure = function () {
        return [
            {
                name: 'species',
                displayName: 'Animal Species',
                regex: '^[a-zA-Z]+$',
                regexMessage: 'Name can only contain English characters!',
                description: 'Which species does the animal belong to.',
                value: 'Horse',
                valueType: 'string',
                readOnly: false
            },
            {
                name: 'age',
                displayName: 'Age',
                description: 'How old is the animal.',
                value: 3,
                valueType: 'number',
                minValue: 0,
                maxValue: 10000,
                readOnly: false
            },
            {
                name: 'carnivore',
                displayName: 'Carnivore',
                description: 'Does the animal eat other animals?',
                value: false,
                valueType: 'boolean',
                readOnly: false
            },
            {
                name: 'classification',
                displayName: 'Classification',
                description: '',
                value: 'Vertebrates',
                valueType: 'string',
                valueItems: [
                    'Vertebrates',
                    'Invertebrates',
                    'Unknown'
                ]
            },
            {
                name: 'color',
                displayName: 'Color',
                description: 'The hex color code for the animal.',
                readOnly: false,
                value: '#FF0000',
                regex: '^#([A-Fa-f0-9]{6})$',
                valueType: 'string'
            },
            {
                name: 'anAsset',
                displayName: 'Document',
                description: '',
                value: '',
                valueType: 'asset',
                readOnly: false
            }
        ];
    };


    /**
     * Main function for the plugin to execute. This will perform the execution.
     * Notes:
     * - Always log with the provided logger.[error,warning,info,debug].
     * - Do NOT put any user interaction logic UI, etc. inside this method.
     * - callback always has to be called even if error happened.
     *
     * @param {function(string, plugin.PluginResult)} callback - the result callback
     */
    ImportTorch.prototype.main = function (callback) {
        // Use self to access core, project, result, logger etc from PluginBase.
        // These are all instantiated at this point.
        var self = this,
            nodeObject;


        // Using the logger.
        self.logger.debug('This is a debug message.');
        self.logger.info('This is an info message.');
        self.logger.warn('This is a warning message.');
        self.logger.error('This is an error message.');

        // Using the coreAPI to make changes.

        nodeObject = self.activeNode;

        self.core.setAttribute(nodeObject, 'name', 'My new obj');
        self.core.setRegistry(nodeObject, 'position', {x: 70, y: 70});


        // Obtain the current user configuration.
        var currentConfig = self.getCurrentConfig();
        self.logger.info('Current configuration ' + JSON.stringify(currentConfig, null, 4));

        // This will save the changes. If you don't want to save;
        // exclude self.save and call callback directly from this scope.
        self.save('ImportTorch updated model.', function (err) {
            if (err) {
                callback(err, self.result);
                return;
            }
            self.result.setSuccess(true);
            callback(null, self.result);
        });

    };

    return ImportTorch;
});