#!/usr/bin/env bash
DEEPFORGE_DEPLOYMENT_DIR="$(realpath "$(dirname "$0")")"
export DEEPFORGE_DEPLOYMENT_DIR

. ~/.nvm/nvm.sh

SERVER_NAME="server"

if [[ $1 = "stable" ]]; then
   SERVER_NAME="server_stable"
fi;

# Merging the custom override yml file
yaml-merge docker/docker-compose.yml "$DEEPFORGE_DEPLOYMENT_DIR"/docker-compose-overrides.yml > custom-docker-compose.yml

# Pulling the latest docker image, stopping the server, removing and restarting it
docker-compose --file custom-docker-compose.yml -p deepforge pull $SERVER_NAME
docker-compose --file custom-docker-compose.yml -p deepforge stop $SERVER_NAME
docker-compose --file custom-docker-compose.yml -p deepforge rm -f $SERVER_NAME
docker-compose --file custom-docker-compose.yml -p deepforge up -d $SERVER_NAME

docker image prune -f
