/*globals define */
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue May 24 2016 10:15:19 GMT-0500 (CDT).
 */

define([
    'panels/PipelineEditor/PipelineEditorControl',
    'underscore'
], function (
    PipelineEditorControl,
    _
) {

    'use strict';

    var ExecutionViewControl;

    ExecutionViewControl = function (options) {
        PipelineEditorControl.call(this, options);
        // TODO: Set read only (rm selection's action btns)
    };

    _.extend(ExecutionViewControl.prototype, PipelineEditorControl.prototype);

    /* * * * * * * * Visualizer content update callbacks * * * * * * * */
    ExecutionViewControl.prototype.TERRITORY_RULE = {children: 4};
    ExecutionViewControl.prototype.DEFAULT_DECORATOR = 'JobDecorator';

    ExecutionViewControl.prototype.updateTerritory = function() {
        var nodeId = this._currentNodeId;

        // activeNode rules
        this._territories = {};

        this._territoryId = this._client.addUI(this, events => {
            this._eventCallback(events);
        });

        this._territories[nodeId] = {children: 0};  // Territory "rule"
        this._client.updateTerritory(this._territoryId, this._territories);

        this._territories[nodeId] = this.TERRITORY_RULE;
        this._client.updateTerritory(this._territoryId, this._territories);
    };

    return ExecutionViewControl;
});
