/*globals define, WebGMEGlobal*/
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue May 24 2016 10:15:19 GMT-0500 (CDT).
 */

define([
    'panels/PipelineEditor/PipelineEditorControl',
    'underscore',
    'js/NodePropertyNames'
], function (
    PipelineEditorControl,
    _,
    nodePropertyNames
) {

    'use strict';

    var ExecutionViewControl;

    ExecutionViewControl = function (options) {
        PipelineEditorControl.call(this, options);
        // TODO: Set read only (rm selection's action btns)
    };

    _.extend(ExecutionViewControl.prototype, PipelineEditorControl.prototype);

    /* * * * * * * * Visualizer content update callbacks * * * * * * * */
    ExecutionViewControl.prototype.TERRITORY_RULE = {children: 4};

    return ExecutionViewControl;
});
