/*globals define */
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue May 17 2016 11:25:46 GMT-0400 (EDT).
 */

define([
    'panels/EasyDAG/EasyDAGControl',
    'js/NodePropertyNames',
    'js/Utils/ComponentSettings',
    'underscore'
], function (
    EasyDAGControl,
    nodePropertyNames,
    ComponentSettings,
    _
) {

    'use strict';

    var ArchEditorControl,
        DEFAULT_CONFIG = {
            DefaultColor: '#ffb74d',
            LayerColors: {
                Containers: '#ffb74d',
                Module: '#ba68c8',
                ConvLayer: '#2196f3',
                SimpleLayer: '#ff9100',
                TransferLayer: '#80deea',
                MiscLayers: '#ce93d8',
                Criterion: '#7e57c2'
            }
        };

    ArchEditorControl = function (options) {
        EasyDAGControl.call(this, options);
        this._config = DEFAULT_CONFIG;
        ComponentSettings.resolveWithWebGMEGlobal(this._config, this.getComponentId());
    };

    _.extend(ArchEditorControl.prototype, EasyDAGControl.prototype);

    ArchEditorControl.prototype.TERRITORY_RULE = {children: 1};
    ArchEditorControl.prototype.getComponentId = function() {
        return 'ArchEditor';
    };

    ArchEditorControl.prototype._getObjectDescriptor = function(id) {
        var desc = EasyDAGControl.prototype._getObjectDescriptor.call(this, id);

        // Filter attributes
        if (!desc.isConnection) {
            var allAttrs = desc.attributes,
                names = Object.keys(allAttrs),
                schema;

            desc.attributes = {};
            for (var i = names.length; i--;) {
                schema = this._client.getAttributeSchema(id, names[i]);
                if (names[i] === 'name' || schema.hasOwnProperty('argindex')) {
                    desc.attributes[names[i]] = allAttrs[names[i]];
                }
            }

            // Add layer type (base class's base class)
            desc.layerType = null;
            if (desc.baseName) {
                var node = this._client.getNode(id),
                    base = this._client.getNode(node.getMetaTypeId()),
                    layerType = this._client.getNode(base.getBaseId()),
                    color;

                desc.baseName = base.getAttribute(nodePropertyNames.Attributes.name);
                if (layerType) {
                    desc.layerType = layerType.getAttribute(nodePropertyNames.Attributes.name);

                    color = this._config.LayerColors[desc.layerType];
                    if (!color) {
                        this._logger.warn(`No color found for ${desc.layerType}`);
                        color = this._config.DefaultColor;
                    }
                    desc.color = color;
                }
            }
        }
        return desc;
    };

    ArchEditorControl.prototype._getValidInitialNodes = function() {
        return this._client.getChildrenMeta(this._currentNodeId).items
            // For now, anything is possible!
            // FIXME
            .map(info => this._getAllDescendentIds(info.id))
            .reduce((prev, curr) => prev.concat(curr))
            // Filter all abstract nodes
            .filter(nodeId => {
                return !this._client.getNode(nodeId).isAbstract();
            })
            .map(id => this._getObjectDescriptor(id))
            .filter(obj => !obj.isConnection && obj.name !== 'Connection');
    };

    return ArchEditorControl;
});
