/*globals define, WebGMEGlobal*/
/*jshint browser: true*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue May 17 2016 11:25:46 GMT-0400 (EDT).
 */

define([
    'panels/EasyDAG/EasyDAGControl',
    'underscore'
], function (
    EasyDAGControl,
    _
) {

    'use strict';

    var ArchEditorControl;

    ArchEditorControl = function (options) {
        EasyDAGControl.call(this, options);
    };

    _.extend(ArchEditorControl.prototype, EasyDAGControl.prototype);

    ArchEditorControl.prototype._getObjectDescriptor = function(id) {
        var desc = EasyDAGControl.prototype._getObjectDescriptor.call(this, id);

        // Filter attributes
        if (!desc.isConnection) {
            var allAttrs = desc.attributes,
                names = Object.keys(allAttrs),
                schema;

            desc.attributes = {};
            for (var i = names.length; i--;) {
                schema = this._client.getAttributeSchema(id, names[i]);
                if (names[i] === 'name' || schema.hasOwnProperty('argindex')) {
                    desc.attributes[names[i]] = allAttrs[names[i]];
                }
            }
        }
        return desc;
    };

    ArchEditorControl.prototype._getValidInitialNodes = function() {
        return this._client.getChildrenMeta(this._currentNodeId).items
        // For now, anything is possible!
	// FIXME
        .map(info => this._getAllDescendentIds(info.id))
        .reduce((prev, curr) => prev.concat(curr))
	// Filter all abstract nodes
	.filter(nodeId => {
	    return !this._client.getNode(nodeId).isAbstract();
	})
	.map(id => this._getObjectDescriptor(id))
	.filter(obj => !obj.isConnection && obj.name !== 'Connection');
    };

    return ArchEditorControl;
});
