/*globals define */
/*jshint browser: true*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Wed Jun 01 2016 14:44:21 GMT-0500 (CDT).
 */

define([
    'widgets/TextEditor/TextEditorWidget',
    'underscore',
    'css!./styles/SerializeEditorWidget.css'
], function (
    TextEditorWidget,
    _
) {
    'use strict';

    var SerializeEditorWidget;
        //WIDGET_CLASS = 'serialize-editor';

    SerializeEditorWidget = function (logger, container) {
        TextEditorWidget.call(this, logger, container);
    };

    _.extend(SerializeEditorWidget.prototype, TextEditorWidget.prototype);

    SerializeEditorWidget.prototype.getHeader = function(desc) {
        return [
            `-- The serialization function for ${desc.name}`,
            '-- Globals:',
            '--   `path` - target filename',
            `--   \`data\` - the ${desc.name} to store`
        ].join('\n');
    };

    return SerializeEditorWidget;
});
